name: web
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <eric@ericwindmill.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  angular_router: ^2.0.0-alpha+22
  angular_bloc: ^0.9.0
  common:
    path: ../../common
  markdown: ^2.0.0

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
