name: cms_server
description: An empty Aqueduct application.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  json_serializable: ^3.0.0
  json_annotation: ^2.4.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0